<a href="https://colab.research.google.com/github/Joshi-Atharva/Sentiment-analysis/blob/main/Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
# Mounting the drive to use the files and images
import os
import csv
os.chdir('/content/drive/MyDrive/Sentiment analysis/')
print(os.listdir())
# rom extract_csv import extract_csv, split
from extract_bin import extract_bin, split
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

Mounted at /content/drive
['Sentiment_analysis.ipynb', 'extract_bin.py', 'amazon_cells_labelled.txt', '__pycache__']


In [2]:
file_path = 'amazon_cells_labelled.txt'
data = extract_bin(file_path)
inputs = data.inputs
labels = data.labels
# data = extract_bin("train_set_sentiment_final.txt")
# input300 = data.inputs
# labels300 = data.labels
# inputs.extend(input300)
# labels.extend(labels300)

split_object = split(inputs, labels, 800)
train_inputs = split_object.train_set_inputs
train_labels = split_object.train_set_labels
test_inputs = split_object.test_set_inputs
test_labels = split_object.test_set_labels
print(train_inputs)
print(train_labels)

['So there is no way for me to plug it in here in the US unless I go by a converter.\t', 'Good case, Excellent value.\t', 'Great for the jawbone.\t', 'Tied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!\t', 'The mic is great.\t', 'I have to jiggle the plug to get it to line up right to get decent volume.\t', 'If you have several dozen or several hundred contacts, then imagine the fun of sending each of them one by one.\t', 'If you are Razr owner...you must have this!\t', 'Needless to say, I wasted my money.\t', 'What a waste of money and time!.\t', 'And the sound quality is great.\t', 'He was very impressed when going from the original battery to the extended battery.\t', 'If the two were seperated by a mere 5+ ft I started to notice excessive static and garbled sound from the headset.\t', 'Very good quality though\t', 'The design is very odd, as the ear "clip" is not very comfortable at all.\t', 'Highly recommend for any one who has a blue tooth phone.\t', 

In [3]:

tokenizer = Tokenizer()
tokenizer.fit_on_texts(train_inputs)
print(tokenizer.word_index)
tokenized_inputs = tokenizer.texts_to_sequences(train_inputs)
print(tokenized_inputs)


{'the': 1, 'i': 2, 'and': 3, 'it': 4, 'is': 5, 'a': 6, 'this': 7, 'to': 8, 'phone': 9, 'my': 10, 'for': 11, 'of': 12, 'great': 13, 'not': 14, 'with': 15, 'very': 16, 'in': 17, 'on': 18, 'was': 19, 'you': 20, 'that': 21, 'good': 22, 'have': 23, 'quality': 24, 'product': 25, 'battery': 26, 'works': 27, 'but': 28, 'sound': 29, 'headset': 30, 'as': 31, 'well': 32, 'all': 33, 'had': 34, 'are': 35, 'one': 36, 'use': 37, 'would': 38, 'has': 39, 'if': 40, 'so': 41, "i've": 42, 'like': 43, 'than': 44, 'from': 45, 'be': 46, 'after': 47, 'work': 48, 'ear': 49, 'your': 50, 'no': 51, 'case': 52, 'recommend': 53, 'up': 54, 'or': 55, 'time': 56, 'price': 57, '2': 58, "don't": 59, 'me': 60, 'excellent': 61, "it's": 62, 'service': 63, 'new': 64, 'really': 65, 'more': 66, 'at': 67, 'best': 68, 'nice': 69, 'get': 70, 'any': 71, 'too': 72, 'love': 73, 'worked': 74, 'also': 75, 'am': 76, 'charger': 77, 'out': 78, 'only': 79, 'buy': 80, 'just': 81, 'item': 82, "i'm": 83, 'an': 84, 'ever': 85, 'money': 86, '

In [4]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_inputs = pad_sequences(tokenized_inputs, padding='post')
train_labels = tf.convert_to_tensor(train_labels)
print(padded_inputs)


[[  41  161    5 ...    0    0    0]
 [  22   52   61 ...    0    0    0]
 [  13   11    1 ...    0    0    0]
 ...
 [   6   22   24 ...    0    0    0]
 [ 679  222    1 ...    0    0    0]
 [   2  198 1682 ...    0    0    0]]


In [5]:
X = padded_inputs
Y = train_labels
print(X.shape)
print(Y.shape)
print(Y)

(800, 30)
(800,)
tf.Tensor(
[0 1 1 0 1 0 0 1 0 0 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1
 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1
 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1
 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 1 1 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0 0
 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 1 1
 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 0 1 1
 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1 1
 1 1 0 0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 1 1
 0 1 1 0 0 0 1 0 1 0 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 1 1 0 1 0
 1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 0 0 0 0 0 1
 1 1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1 0

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [7]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=128))
model.add(LSTM(units=64, return_sequences=True))
model.add(LSTM(units=64))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# input_dim specify the vocab count, output_dim the dense vector dim, input_length the number of words in the sentence

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.fit(X, Y, epochs = 15)

Epoch 1/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - accuracy: 0.4790 - loss: 0.6947
Epoch 2/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.5560 - loss: 0.6869
Epoch 3/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8653 - loss: 0.3725
Epoch 4/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.9496 - loss: 0.2106
Epoch 5/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9848 - loss: 0.0740
Epoch 6/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.9956 - loss: 0.0264
Epoch 7/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - accuracy: 0.9939 - loss: 0.0252
Epoch 8/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 1.0000 - loss: 0.0036
Epoch 9/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.9959 - loss: 0.0139
Epoch 10/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.9888 - loss: 0.0494
Epoch 11/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.9352 - loss: 0.2785
Epoch 12/15
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy:

In [11]:

def predict(model, tokenizer, input):
  tokenized_inputs = tokenizer.texts_to_sequences(input)
  padded_inputs = pad_sequences(tokenized_inputs, padding='post')
  predictions = model.predict(padded_inputs)
  return predictions

In [12]:
accuracy = 0
for i in range(len(test_inputs)):
    print(i, ':', test_inputs[i])
    prediction = predict(model, tokenizer, [test_inputs[i]])
    print(prediction)

    if prediction > 0.5:
        predicted_label = 1
        print("Positive")
    else:
        predicted_label = 0
        print("Negative")
    if( predicted_label == test_labels[i]):
        accuracy += 1
    print(predict(model, tokenizer, [test_inputs[i]]))
accuracy = accuracy/len(test_inputs)
print(f'accuracy = {accuracy}')

0 : Good , works fine.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step
[[0.5799374]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.5799374]]
1 : For the price this was a great deal.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step
[[0.6787751]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.6787751]]
2 : Great price, too!	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[[0.5932618]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[0.5932618]]
3 : If there is a wind, it is completely useless.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[0.36989638]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.36989638]]
4 : Yes it's shiny on front side - and I love it!	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.6635621]]
Positive
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.6635621]]
5 : Does Not Work.	
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.4990934]]
Negative
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[0.4990934]]
6 : At first I thought I was grtting a good deal at $7.44, until I plugged it into my phone (V3c Razr).	
1/

In [13]:
text = "good product given by prajwal"
text_list = text.split()
for i in range(len(text_list)):
    if(text_list[i] not in tokenizer.word_index):
        print(text_list[i], ':not found')

prediction = predict(model, tokenizer, [text])
print(prediction)
if(prediction > 0.5):
    print("Positive")
else:
    print("Negative")

prajwal :not found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[0.5576793]]
Positive


In [14]:
print(len(tokenizer.word_index))


1684


In [15]:

os.listdir()

['Sentiment_analysis.ipynb',
 'extract_bin.py',
 'amazon_cells_labelled.txt',
 '__pycache__']